### ISSUE TITLE
Animal name generator tweaks

### ISSUE THREAD

**Issue by dkambersky** [Terasology/NameGenerator#17]
Right now the animal name generator works, but 

- [ ] the sourcelist combines both male and female names in one file, so the names at times come out a combination of those. There should be separate source files for both sexes.

- [ ] the animals get surnames from the same sourcelist. They probably shouldn't even *have* surnames.

This is a simple change for someone with the workspace set up, I'm noting it down so it doesn't get forgotten.

**Comment by Cervator** [comment]
Closing as completed by #18 :-)
